### ISSUE TITLE
How to include 32k model support?

### ISSUE THREAD

**Issue by dmikushin** [parallelo3301/zulip-chatgpt-bot#7]
Hi @parallelo3301 ,

32k models bring in a lot more context, therefore I looked into your code regarding the possibility of 32k models enablement. It all looks straightforward, except this part:

```python3
    model_tokens = {
        # input limit for GPT-3.5 Turbo (context 4k, prompt 2.5k, response 1.5k)
        'gpt-3.5-turbo': 2500,
        'gpt-3.5-turbo-0301': 2500,
        # input limit for GPT-4 (context 8k, prompt 6k, response 2k)
        'gpt-4': 6000,
        'gpt-4-0314': 6000,
        'gpt-4-0613': 6000,
    }
```

I don't understand where these `2500` and `6000` values are coming from. They are not referenced anywhere on the OpenAI website. So, have you calculated them? What should be the value for `gpt-4-32k-0613` model?

**Comment by parallelo3301** [comment]
Hey @dmikushin, they are my particular limits. 🙂 

As you have a limited context window (4k, 8k, 32k, 128k), you must fit your prompt WITH the output in it. So e.g. having a 4,000 context, and sending 3,900 input tokens will leave you with 100 tokens for the output. Hence the artificial limit for input tokens, but feel free to change it locally. This would ideally go to some external configuration file.

To answer your question for `gpt-4-32k-0613` - it depends solely on you. If you **need** to provide long context to it, and are ok with shorter / cut out answer, set it high like 30,000. If you are not providing that much context, you might leave more space for the answer. It depends on your organization / how you use Zulip. If you want to summarize often, it might be better to provide more context. If you generate a code with it, having a balanced limit (16k input, 16k output) might be better.

And for example [gpt-4-1106-preview](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) has 128k context window, but **Returns a maximum of 4,096 output tokens.** So the `model_tokens` limit can be 124k.

Two tips:
If you not get the whole answer, just write something like `@AI continue`.

Bot provides the context from previous messages by default. Having a high limit means that it will most probably always fill it with previous messages (as people are lazy/don't know how to use `!new` subcommand to not include previous messages), so you might end paying a lot of money unnecessarily even for single line question. That's why having more balanced setting might be better too, but like I said, depends on your org needs.

**Comment by dmikushin** [comment]
Hi @parallelo3301 , thanks,

> having a 4,000 context, and sending 3,900 input tokens will leave you with 100 tokens for the output

> [gpt-4-1106-preview](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) has 128k context window, but Returns a maximum of 4,096 output tokens

So if the model does not specify any extra limits, the remaining tokens are those that can be used for the response.

**Comment by parallelo3301** [comment]
Yes, I believe it should work like that.
